def generate_go_source(importpath, entries):
    """Generates the Go source code for a runfiles library.

    Args:
        importpath: The Go importpath of the generated library.
        entries: A list of structs containing `name`, `doc`, and `short_path`.

    Returns:
        A string containing the generated Go source code.
    """
    pkg_name = importpath.split("/")[-1]
    
    lines = [
        "// Code generated by rules_runfiles_codegen. DO NOT EDIT.",
        "package {}".format(pkg_name),
        "",
        "import (",
        "\t\"log\"",
        "",
        "\t\"github.com/bazelbuild/rules_go/go/runfiles\"",
        ")",
        "",
        "var (",
    ]
    
    for e in entries:
        if e.doc:
            lines.append("\t// {}".format(e.doc))
        lines.append("\t{} string".format(e.name))
    
    lines.append(")")
    lines.append("")
    
    lines.append("func init() {")
    lines.append("\tvar err error")
    
    for e in entries:
        # short_path contains the workspace name prefix if it's external, or just the relative path from workspace root.
        # rules_go's runfiles expects the workspace relative path (for current repo) or "workspace_name/..." for external.
        # `short_path` is usually `some/path` (for current workspace) or `../repo/some/path` for external.
        # A robust way is to use `Rlocation` which resolves paths.
        
        # When Bazel compiles, runfiles.Rlocation expects the path in the format "workspace_name/package/file".
        # However, `short_path` is often relative to the execution root. Let's rely on it for now.
        # Wait, if we use e.short_path, we can pass it to runfiles.Rlocation. 
        # But wait, runfiles.Rlocation expects a runfiles-root relative path, which is usually `workspace_name/path`.
        # `e.workspace_name` and `e.short_path` can construct it.
        # Let's assume `e.runfiles_path` is the correct path string.
        lines.append("\t{}, err = runfiles.Rlocation(\"{}\")".format(e.name, e.runfiles_path))
        lines.append("\tif err != nil {")
        lines.append("\t\tlog.Fatalf(\"Failed to locate runfile {}: %v\", err)")
        lines.append("\t}")
    
    lines.append("}")
    
    return "\n".join(lines)
