# Go code emitter for rules_runfile_codegen.
load("//internal/emitters:template.bzl", "render")
load("//internal/emitters:utils.bzl", "escape_go_string")

def _header_part(package_name, extra_imports):
    return render(
        """// Code generated by rules_runfile_codegen. DO NOT EDIT.

// Package {{package_name}} provides type-safe access to Bazel runfiles.
package {{package_name}}

import (
	"fmt"
{{extra_imports}}	"github.com/bazelbuild/rules_go/go/runfiles"
)

// Runfile represents a resolved runfile.
type Runfile struct {
	absPath string
}

// Path returns the resolved absolute path of the runfile.
func (r Runfile) Path() string {
	return r.absPath
}""",
        package_name = package_name,
        extra_imports = extra_imports,
    )

def _executable_part():
    return """// ExecutableRunfile represents a resolved executable runfile.
type ExecutableRunfile struct {
	Runfile
}

// Cmd returns an *exec.Cmd pre-configured to run this executable,
// with the Bazel runfiles environment variables already propagated.
func (e ExecutableRunfile) Cmd(args ...string) *exec.Cmd {
	cmd := exec.Command(e.Path(), args...)
	if env, err := runfiles.Env(); err == nil {
		cmd.Env = append(os.Environ(), env...)
	}
	return cmd
}"""

def _variables_part(variables_str):
    return render(
        """var (
{{variables}}
)""",
        variables = variables_str,
    )

def _init_part(assignments_str):
    return render(
        """func init() {
	reg, err := runfiles.New()
	if err != nil {
		panic(fmt.Sprintf("failed to initialize runfiles: %v", err))
	}

{{assignments}}
}""",
        assignments = assignments_str,
    )

def _helpers_part(executable_helper_str):
    return render(
        """func mustResolve(reg *runfiles.Runfiles, rlocationPath string) Runfile {
	absPath, err := reg.Rlocation(rlocationPath)
	if err != nil {
		panic(fmt.Sprintf("failed to resolve runfile %q: %v", rlocationPath, err))
	}
	return Runfile{absPath: absPath}
}
{{executable_helper}}""",
        executable_helper = executable_helper_str,
    )

def _executable_helper_part():
    return """func mustResolveExecutable(reg *runfiles.Runfiles, rlocationPath string) ExecutableRunfile {
	absPath, err := reg.Rlocation(rlocationPath)
	if err != nil {
		panic(fmt.Sprintf("failed to resolve executable runfile %q: %v", rlocationPath, err))
	}
	return ExecutableRunfile{Runfile{absPath: absPath}}
}"""

def _validate_identifier(name, label):
    """Validates that a string is a valid Go identifier for export (starts with uppercase)."""
    if not name:
        fail("Runfile name cannot be empty in '%s'." % label)
    if not name[0].isupper():
        fail("Runfile name '%s' in '%s' must start with an uppercase letter to be exported in Go." % (name, label))
    for char in name.elems() if hasattr(name, "elems") else name:
        if not (char.isalnum() or char == "_"):
            fail("Runfile name '%s' in '%s' is not a valid Go identifier. It must only contain alphanumeric characters and underscores." % (name, label))

def emit_go(importpath, entries):
    """Generates the Go source code for a runfiles library.

    Args:
        importpath: The Go import path for the generated package (e.g., "github.com/user/repo/pkg").
            This is used to derive the Go package name by taking the last component
            and sanitizing it to be a valid Go identifier.
        entries: A list of dicts representing the runfile entries, as returned by
            `analyze_entries`. Each dict must contain:
            - "name": The Go identifier name (must be exported/uppercase).
            - "runfile_path": The resolved rlocation path of the runfile.
            - "is_executable": Boolean indicating if the target is executable.
            - "doc": Optional documentation string for the variable.
            - "label": The Bazel label of the target (used for source comments).

    Returns:
        A string containing the complete, formatted Go source code.
    """
    # Sanitise package name (handling trailing slashes and digit prefixes)
    if importpath.endswith("/"):
        importpath = importpath[:-1]

    package_name = importpath.split("/")[-1]
    sanitized_package_name = ""
    for i in range(len(package_name)):
        char = package_name[i]
        if char.isalnum():
            sanitized_package_name += char
        else:
            sanitized_package_name += "_"

    if sanitized_package_name and sanitized_package_name[0].isdigit():
        sanitized_package_name = "_" + sanitized_package_name

    has_executable = any([e["is_executable"] for e in entries])

    # 1. Header
    extra_imports = ""
    if has_executable:
        extra_imports = '\t"os"\n\t"os/exec"\n'
    header = _header_part(sanitized_package_name, extra_imports)

    # 2. Executable struct (optional)
    executable_struct = None
    if has_executable:
        executable_struct = _executable_part()

    # 3. Variables
    var_blocks = []
    for entry in entries:
        # Validate Go identifier
        _validate_identifier(entry["name"], entry["label"])

        lines = []
        if entry["doc"]:
            doc_lines = entry["doc"].split("\n")
            lines.append("\t// %s is %s" % (entry["name"], doc_lines[0]))
            for line in doc_lines[1:]:
                lines.append("\t// %s" % line)
        lines.append("\t// Source: %s" % entry["label"])
        if entry["is_executable"]:
            lines.append("\t%s ExecutableRunfile" % entry["name"])
        else:
            lines.append("\t%s Runfile" % entry["name"])
        var_blocks.append("\n".join(lines))
    
    variables_str = "\n\n".join(var_blocks) + "\n"
    variables_block = _variables_part(variables_str)

    # 4. Init
    assignments = []
    for entry in entries:
        escaped_path = escape_go_string(entry["runfile_path"])
        if entry["is_executable"]:
            assignments.append('\t%s = mustResolveExecutable(reg, "%s")' % (entry["name"], escaped_path))
        else:
            assignments.append('\t%s = mustResolve(reg, "%s")' % (entry["name"], escaped_path))
    assignments_str = "\n".join(assignments)
    init_block = _init_part(assignments_str)

    # 5. Helpers
    if has_executable:
        helpers_block = _helpers_part("\n" + _executable_helper_part())
    else:
        helpers_block = _helpers_part("")

    # Assemble all parts
    parts = []
    parts.append(header)
    if executable_struct:
        parts.append(executable_struct)
    parts.append(variables_block)
    parts.append(init_block)
    parts.append(helpers_block)

    return "\n\n".join(parts) + "\n"
