# Go code emitter for rules_runfile_codegen.
load("//internal/emitters:template.bzl", "render")
load("//internal/emitters:utils.bzl", "escape_go_string")

def _header_part(package_name):
    return render(
        """// Code generated by rules_runfile_codegen. DO NOT EDIT.

// Package {{package_name}} provides type-safe access to Bazel runfiles.
package {{package_name}}

import (
	"github.com/meta-programming/rules_runfiles_codegen/go/runfile"
)""",
        package_name = package_name,
    )

def _variables_part(variables_str):
    return render(
        """var (
{{variables}}
)""",
        variables = variables_str,
    )

def _validate_identifier(name, label):
    """Validates that a string is a valid Go identifier for export (starts with uppercase)."""
    if not name:
        fail("Runfile name cannot be empty in '%s'." % label)
    if not name[0].isupper():
        fail("Runfile name '%s' in '%s' must start with an uppercase letter to be exported in Go." % (name, label))
    for char in name.elems() if hasattr(name, "elems") else name:
        if not (char.isalnum() or char == "_"):
            fail("Runfile name '%s' in '%s' is not a valid Go identifier. It must only contain alphanumeric characters and underscores." % (name, label))

def emit_go(importpath, entries):
    """Generates the Go source code for a runfiles library.

    Args:
        importpath: The Go import path for the generated package (e.g., "github.com/user/repo/pkg").
            This is used to derive the Go package name by taking the last component
            and sanitizing it to be a valid Go identifier.
        entries: A list of dicts representing the runfile entries, as returned by
            `analyze_entries`. Each dict must contain:
            - "name": The Go identifier name (must be exported/uppercase).
            - "runfile_path": The resolved rlocation path of the runfile.
            - "is_executable": Boolean indicating if the target is executable.
            - "doc": Optional documentation string for the variable.
            - "label": The Bazel label of the target (used for source comments).

    Returns:
        A string containing the complete, formatted Go source code.
    """
    # Sanitise package name (handling trailing slashes and digit prefixes)
    if importpath.endswith("/"):
        importpath = importpath[:-1]

    package_name = importpath.split("/")[-1]
    sanitized_package_name = ""
    for i in range(len(package_name)):
        char = package_name[i]
        if char.isalnum():
            sanitized_package_name += char
        else:
            sanitized_package_name += "_"

    if sanitized_package_name and sanitized_package_name[0].isdigit():
        sanitized_package_name = "_" + sanitized_package_name

    # 1. Header
    header = _header_part(sanitized_package_name)

    # 2. Variables (initialized inline)
    var_blocks = []
    for entry in entries:
        # Validate Go identifier
        _validate_identifier(entry["name"], entry["label"])

        lines = []
        if entry["doc"]:
            doc_lines = entry["doc"].split("\n")
            lines.append("\t// %s is %s" % (entry["name"], doc_lines[0]))
            for line in doc_lines[1:]:
                lines.append("\t// %s" % line)
        lines.append("\t// Source: %s" % entry["label"])
        
        escaped_path = escape_go_string(entry["runfile_path"])
        if entry["is_executable"]:
            lines.append('\t%s = runfile.NewExecutableSpec("%s")' % (entry["name"], escaped_path))
        else:
            lines.append('\t%s = runfile.NewSpec("%s")' % (entry["name"], escaped_path))
        var_blocks.append("\n".join(lines))
    
    variables_str = "\n\n".join(var_blocks) + "\n"
    variables_block = _variables_part(variables_str)

    # Assemble all parts
    parts = [
        header,
        variables_block,
    ]

    return "\n\n".join(parts) + "\n"

