# Kotlin code emitter for rules_runfile_codegen.
load("//internal:emitters/template.bzl", "render")
load("//internal:emitters/utils.bzl", "escape_kotlin_string", "sanitize_kdoc")

def _kotlin_header_part(package):
    return render(
        """// Code generated by rules_runfile_codegen. DO NOT EDIT.
// This file provides type-safe access to Bazel runfiles.
package {{package}}

import com.google.devtools.build.runfiles.Runfiles""",
        package = package,
    )

def _kotlin_object_template(object_name, members_str):
    return render(
        """object {{object_name}} {
{{members}}

}""",
        object_name = object_name,
        members = members_str,
    )

def _kotlin_runfiles_field():
    return """    private val _runfiles: Runfiles = try {
        Runfiles.create()
    } catch (e: java.io.IOException) {
        throw java.lang.RuntimeException("Failed to create runfiles registry", e)
    }"""

def _kotlin_runfile_class():
    return """    open class Runfile(val path: String) {
        val jvmPath: java.nio.file.Path by lazy { java.nio.file.Paths.get(path) }
    }"""

def _kotlin_executable_class(object_name):
    return render(
        """    class ExecutableRunfile(path: String) : Runfile(path) {
        fun processBuilder(vararg args: String): ProcessBuilder {
            val pb = ProcessBuilder(path, *args)
            pb.environment().putAll({{object_name}}._runfiles.envVars)
            return pb
        }
    }""",
        object_name = object_name,
    )

def _kotlin_resolve_helper():
    return """    private fun _mustResolve(rlocationPath: String): Runfile {
        val absPath = _runfiles.rlocation(rlocationPath)
            ?: throw java.lang.RuntimeException("Failed to resolve runfile: $rlocationPath")
        return Runfile(absPath)
    }"""

def _kotlin_resolve_executable_helper():
    return """    private fun _mustResolveExecutable(rlocationPath: String): ExecutableRunfile {
        val absPath = _runfiles.rlocation(rlocationPath)
            ?: throw java.lang.RuntimeException("Failed to resolve executable runfile: $rlocationPath")
        return ExecutableRunfile(absPath)
    }"""

_KOTLIN_KEYWORDS = [
    "as", "as?", "break", "class", "continue", "do", "else", "false", "for",
    "fun", "if", "in", "!in", "is", "!is", "null", "object", "package",
    "return", "super", "this", "throw", "true", "try", "typealias", "val",
    "var", "when", "while", "interface", "import"
]

_KOTLIN_RESERVED_NAMES = ["Runfile", "ExecutableRunfile", "_runfiles", "_mustResolve", "_mustResolveExecutable"]

def _validate_identifier(name, label, is_object = False):
    """Validates that a string is a valid Kotlin identifier."""
    if not name:
        fail("Identifier name cannot be empty in '%s'." % label)
    if name in _KOTLIN_KEYWORDS:
        fail("Identifier '%s' in '%s' is a Kotlin keyword and cannot be used." % (name, label))
    
    if not is_object:
        if name in _KOTLIN_RESERVED_NAMES:
            fail("Runfile name '%s' in '%s' is reserved in Kotlin and cannot be used." % (name, label))

    first_char = name[0]
    if not (first_char.isalpha() or first_char == '_'):
        fail("Identifier '%s' in '%s' must start with a letter or underscore for Kotlin." % (name, label))
    
    for char in name.elems() if hasattr(name, "elems") else name:
        if not (char.isalnum() or char == '_'):
            fail("Identifier '%s' in '%s' is not a valid Kotlin identifier. It must only contain alphanumeric characters and underscores." % (name, label))

def emit_kotlin(package, entries, object_name, rule_label):
    """Generates the Kotlin source code for a runfiles library.

    Args:
        package: The Kotlin package name (e.g., "com.example.project.resources").
            If it contains slashes, they will be converted to dots.
        entries: A list of dicts representing the runfile entries, as returned by
            `analyze_entries`. Each dict must contain:
            - "name": The Kotlin property name (must be a valid identifier).
            - "runfile_path": The resolved rlocation path of the runfile.
            - "is_executable": Boolean indicating if the target is executable.
            - "doc": Optional documentation string for the property.
            - "label": The Bazel label of the target (used for source comments).
        object_name: The name of the Kotlin singleton `object` to generate
            (e.g., "MyResources"). Must be a valid Kotlin identifier.
        rule_label: The Bazel label of the calling rule (used for error messages).

    Returns:
        A string containing the complete, formatted Kotlin source code.
    """
    # Validate object_name
    _validate_identifier(object_name, rule_label, is_object = True)

    # Sanitise package name
    if package.endswith("/"):
        package = package[:-1]
    package = package.replace("/", ".")

    # 1. Header
    header = _kotlin_header_part(package)

    # 2. Members of the object
    members = []
    members.append(_kotlin_runfiles_field())
    members.append(_kotlin_runfile_class())
    members.append(_kotlin_executable_class(object_name))
    members.append(_kotlin_resolve_helper())
    members.append(_kotlin_resolve_executable_helper())

    # 3. Properties
    for entry in entries:
        # Validate Kotlin identifier
        _validate_identifier(entry["name"], entry["label"])

        lines = []
        if entry["doc"]:
            # Sanitize KDoc to prevent comment injection
            doc_lines = sanitize_kdoc(entry["doc"]).split("\n")
            lines.append("    /**")
            for line in doc_lines:
                lines.append("     * %s" % line)
            lines.append("     * Source: %s" % entry["label"])
            lines.append("     */")
        else:
            lines.append("    // Source: %s" % entry["label"])
        
        escaped_path = escape_kotlin_string(entry["runfile_path"])
        
        if entry["is_executable"]:
            lines.append('    val %s: ExecutableRunfile = _mustResolveExecutable("%s")' % (entry["name"], escaped_path))
        else:
            lines.append('    val %s: Runfile = _mustResolve("%s")' % (entry["name"], escaped_path))
        members.append("\n".join(lines))

    # Join all members with double newlines
    members_str = "\n\n".join(members)

    # 4. Assemble Object
    object_block = _kotlin_object_template(object_name, members_str)

    return header + "\n\n" + object_block + "\n"
