load("@rules_go//go:def.bzl", "go_library")
load("@rules_runfile_codegen_core//internal:rules.bzl", "runfile_codegen")

def go_runfile(name, target, doc = ""):
    """Creates a runfile entry configuration for Go code generation.

    This helper function constructs a structured dictionary representing a single runfile
    dependency. It is intended to be passed in the `entries` list of `go_runfile_library`.

    Args:
        name: The Go variable name that will be generated to access this runfile.
            This should follow Go-idiomatic naming conventions (e.g., `ConfigJSON`,
            `TestData`). The generated code will expose this as a public string variable.
        target: The Bazel target label of the runfile (e.g., `//path/to:file.json` or
            `:my_target`). This target will be automatically added to the `data`
            attribute of the underlying `go_library` to ensure it is available at runtime.
        doc: A descriptive comment for the generated Go variable. This will be
            included as a Go docstring on the generated variable, providing context
            for developers using the generated library.

    Returns:
        A dictionary containing "name", "target", and "doc" keys, representing the runfile entry.
    """
    return {
        "name": name,
        "target": target,
        "doc": doc,
    }

def go_runfile_library(name, importpath, entries, **kwargs):
    """Generates a Go library containing compile-time safe accessors for runfiles.

    This macro automates the process of accessing Bazel runfiles in Go. It generates
    a Go source file containing resolved runfile paths, allowing you to access them
    via type-safe variables instead of hardcoded string literals.

    The generated library uses `@rules_go//go/runfiles` to resolve the runfiles at runtime.

    ### Example Usage

    In your `BUILD.bazel`:

    ```bazel
    load("//go:defs.bzl", "go_runfile", "go_runfile_library")

    go_runfile_library(
        name = "my_runfiles",
        importpath = "github.com/example/project/my_runfiles",
        entries = [
            go_runfile(
                name = "ConfigJSON",
                target = "//config:config.json",
                doc = "The main configuration file.",
            ),
            go_runfile(
                name = "HelperTool",
                target = "//tools:helper_tool", # An executable target
                doc = "A helper CLI tool.",
            ),
        ],
    )

    go_binary(
        name = "my_binary",
        srcs = ["main.go"],
        deps = [":my_runfiles"],
    )
    ```

    In your `main.go`:

    ```go
    package main

    import (
        "fmt"
        "os"
        "log"

        "github.com/example/project/my_runfiles"
    )

    func main() {
        // 1. Accessing a regular runfile:
        // Resolve the file safely (returns an error if missing).
        configFile, err := my_runfiles.ConfigJSON.Resolve()
        if err != nil {
            log.Fatalf("Failed to resolve config: %v", err)
        }
        content, err := os.ReadFile(configFile.Path())
        if err != nil {
            log.Fatalf("Failed to read config: %v", err)
        }
        fmt.Printf("Config: %s\\n", content)

        // 2. Running an executable runfile:
        // Use MustResolve() for easy fail-fast access (panics if missing).
        helper := my_runfiles.HelperTool.MustResolve()
        cmd := helper.Cmd("--verbose", "run")
        cmd.Stdout = os.Stdout
        cmd.Stderr = os.Stderr
        if err := cmd.Run(); err != nil {
            log.Fatalf("Helper tool failed: %v", err)
        }
    }
    ```

    Args:
        name: A unique name for this target. The generated `go_library` will have this name.
            A helper target named `{name}_codegen` will also be created.
        importpath: The import path for the generated Go library. This is required by `go_library`.
        entries: A list of runfile entries. Each entry must be a dictionary with `name`, `target`,
            and `doc` keys, typically constructed using the `go_runfile` helper function.
        **kwargs: Additional arguments to propagate to the underlying `go_library` target.
            Common arguments include `visibility`, `testonly`, and `tags`.
            `deps` and `data` will be merged with the automatically generated dependencies.
            `srcs` is not allowed as it is generated by this macro.
    """
    if "srcs" in kwargs:
        fail("Cannot specify 'srcs' in go_runfile_library, they are generated automatically.")

    # Extract parallel lists for the generator rule
    names = [e["name"] for e in entries]
    targets = [e["target"] for e in entries]
    docs = [e["doc"] for e in entries]

    # Propagate testonly and tags
    testonly = kwargs.get("testonly", None)
    tags = kwargs.get("tags", None)

    # Merge data and deps
    user_data = kwargs.pop("data", [])
    user_deps = kwargs.pop("deps", [])

    # Call the core generator rule
    runfile_codegen(
        name = name + "_codegen",
        package = importpath,
        language = "go",
        names = names,
        targets = targets,
        docs = docs,
        testonly = testonly,
        tags = tags,
    )

    # Public Go library
    go_library(
        name = name,
        srcs = [":" + name + "_codegen"],
        importpath = importpath,
        deps = [
            "@rules_runfile_codegen_go//runfile",
        ] + user_deps,  # Merge deps
        data = targets + user_data,  # Merge data
        **kwargs
    )
