load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("@rules_runfile_codegen_core//internal:rules.bzl", "runfile_codegen")

def kt_runfile(name, target, doc = ""):
    """Creates a runfile entry configuration for Kotlin code generation.

    This helper function constructs a structured dictionary representing a single runfile
    dependency. It is intended to be passed in the `entries` list of `kt_jvm_runfile_library`.

    Args:
        name: The Kotlin property name that will be generated to access this runfile.
            This should follow Kotlin-idiomatic naming conventions (e.g., `configJson`,
            `testData`). The generated code will expose this as a property on a Kotlin object.
        target: The Bazel target label of the runfile (e.g., `//path/to:file.json` or
            `:my_target`). This target will be automatically added to the `data`
            attribute of the underlying `kt_jvm_library` to ensure it is available at runtime.
        doc: A descriptive comment for the generated Kotlin property. This will be
            included as a KDoc comment on the generated property.

    Returns:
        A dictionary containing "name", "target", and "doc" keys, representing the runfile entry.
    """
    return {
        "name": name,
        "target": target,
        "doc": doc,
    }

def kt_jvm_runfile_library(name, package, entries, object_name = None, **kwargs):
    """Generates a Kotlin JVM library containing compile-time safe accessors for runfiles.

    This macro automates the process of accessing Bazel runfiles in Kotlin. It generates
    a Kotlin source file containing a singleton `object` with properties that hold the
    resolved runfile paths.

    The generated library uses the official Bazel Java runfiles library (`@bazel_tools//tools/java/runfiles`)
    to resolve the runfiles at runtime.

    ### Example Usage

    In your `BUILD.bazel`:

    ```bazel
    load("//kotlin:defs.bzl", "kt_runfile", "kt_jvm_runfile_library")

    kt_jvm_runfile_library(
        name = "my_runfiles",
        package = "com.example.project.runfiles",
        entries = [
            kt_runfile(
                name = "configJson",
                target = "//config:config.json",
                doc = "The main configuration file.",
            ),
            kt_runfile(
                name = "helperTool",
                target = "//tools:helper_tool", # An executable target
                doc = "A helper CLI tool.",
            ),
        ],
    )

    kt_jvm_binary(
        name = "my_binary",
        srcs = ["Main.kt"],
        deps = [":my_runfiles"],
    )
    ```

    In your `Main.kt`:

    ```kotlin
    package com.example.project

    import com.example.project.runfiles.MyRunfiles

    fun main() {
        // 1. Accessing a regular runfile:
        // Resolve the spec and read its content directly.
        val content = MyRunfiles.configJson.resolve().file.readText()
        println("Content: $content")

        // Or use jvmPath by resolving the spec first
        val configJvmPath = MyRunfiles.configJson.resolve().jvmPath
        
        // 2. Running an executable runfile:
        // Resolve the spec to an Executable, then get the process builder.
        val helper = MyRunfiles.helperTool.resolve()
        val pb = helper.processBuilder("--verbose", "run")
        pb.inheritIO()
        val process = pb.start()
        val exitCode = process.waitFor()
        if (exitCode != 0) {
            error("Helper tool failed with exit code $exitCode")
        }
    }
    ```

    Args:
        name: A unique name for this target. The generated `kt_jvm_library` will have this name.
            A helper target named `{name}_codegen` will also be created.
        package: The Kotlin package name for the generated file.
        entries: A list of runfile entries. Each entry must be a dictionary with `name`, `target`,
            and `doc` keys, typically constructed using the `kt_runfile` helper function.
        object_name: The name of the Kotlin `object` (singleton) that will contain the runfile
            properties. If not specified, it defaults to a PascalCase version of the `name` attribute
            (e.g., `my_runfiles` becomes `MyRunfiles`).
        **kwargs: Additional arguments to propagate to the underlying `kt_jvm_library` target.
            Common arguments include `visibility`, `testonly`, and `tags`.
            `deps` and `data` will be merged with the automatically generated dependencies.
            `srcs` is not allowed as it is generated by this macro.
    """
    if "srcs" in kwargs:
        fail("Cannot specify 'srcs' in kt_jvm_runfile_library, they are generated automatically.")

    # Derive object_name if not provided
    if not object_name:
        # Sanitize name to make it a valid PascalCase Kotlin identifier
        clean_name = ""
        for char in name.elems() if hasattr(name, "elems") else name:
            if char.isalnum() or char == "_":
                clean_name += char
            else:
                clean_name += "_"

        # Split by underscore and capitalize
        parts = [part.capitalize() for part in clean_name.split("_") if part]
        object_name = "".join(parts)

        if not object_name:
            fail("Target name '%s' contains no valid characters for a Kotlin object name." % name)
        if object_name[0].isdigit():
            object_name = "_" + object_name

    # Extract parallel lists for the generator rule
    names = [e["name"] for e in entries]
    targets = [e["target"] for e in entries]
    docs = [e["doc"] for e in entries]

    # Propagate testonly and tags
    testonly = kwargs.get("testonly", None)
    tags = kwargs.get("tags", None)

    # Merge data and deps
    user_data = kwargs.pop("data", [])
    user_deps = kwargs.pop("deps", [])

    # Call the core generator rule
    runfile_codegen(
        name = name + "_codegen",
        package = package,
        language = "kotlin",
        object_name = object_name,
        names = names,
        targets = targets,
        docs = docs,
        testonly = testonly,
        tags = tags,
    )

    # Public Kotlin library
    kt_jvm_library(
        name = name,
        srcs = [":" + name + "_codegen"],  # Use the generator target directly
        deps = [
            "@rules_runfile_codegen_kotlin//runfiles",
        ] + user_deps,
        data = targets + user_data,
        **kwargs
    )
